server:
  port: 7777
  # ssl配置，注意配置ssl后前端的请求协议就要改成https了，因为配置后启动的服务就是https的了，不能用http，否则会报错400
  ssl:
    key-store: classpath:ssl/aiphototo.com.jks
    key-store-password: ls5key83574
    key-store-type: JKS
spring:
  datasource:
    url: jdbc:mysql://150.158.51.28:3306/bg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: liushuqi.123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # 配置redis（该配置为连接服务器上容器的redis，想连接本地redis时直接注释即可，连接本地redis不需要配置，可直接连接）
  redis:
    host: 150.158.51.28
    port: 6379
    password: liushuqi.123456

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag # 逻辑删除字段
      logic-delete-value: 1 # 删除 1
      logic-not-delete-value: 0 # 未删除 0
      id-type: auto # 主键自增用数据库id

#七牛云配置信息
oss:
  accessKey: vEL3a8VYZQylavWzkwM9mhq3bCMEwrilEKQ5ZcJN
  secretKey: upzGpgZ7Z7H5isJH9jFK5aDEUIj_tCfBTG9b1BrY
  httpUrl: http://rzoiflfab.hd-bkt.clouddn.com/
  bucket: aiphototo

#疯兔兔的七牛云oss配置
aioss:
  accessKey: RKnYpdZhSigXQukbo9v3GcAusAr8kgeAgzwMQUuy
  secretKey: 9gO22LfiUla4jdETr01txtHQXv4iXiteSoA8dP4W
  bucket: phototo

#疯兔兔的微信配置
aivx:
  appid: wxae6fd03c53b99951
  appsecret: b6b20875aaf2ce7a20d0d41fb01ecd11
